version: "3"

services:
  preso-slides:
    image: rupakg/preso-slides
    ports:
      - 3999:3999    
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
              
  preso-frontend:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - preso-frontend_auth_data:/etc/nginx/conf.d
    depends_on:
      - preso-slides
    deploy:
      placement:
        constraints:
          - node.hostname == manager1

  source:
    image: containerize/git
    environment: 
      - REPO_LOCAL=/data/git/repos/preso-app
      - REPO_BRANCH=master
      - REPO_REMOTE=https://github.com/rupakg/preso-app.git
    tty: true
    volumes: 
      - preso-frontend_auth_data:/data/git/repos/preso-app/preso-auth
    deploy:
      placement:
        constraints:
          - node.hostname == manager1      

volumes:
  preso-frontend_auth_data: {}